services:
  ## POSTGRESQL
  postgresql:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: bootcamp_db
      POSTGRES_USER: dev_dew
      POSTGRES_PASSWORD: password
    volumes:
      # แก้จาก /var/lib/postgresql/data เป็น /var/lib/postgresql เฉยๆ
      - ./postgres_data:/var/lib/postgresql
      - ./script:/docker-entrypoint-initdb.d

    networks:
      - local-network
networks:
  local-network: